arb-dir: lib/l10n
<<<<<<< HEAD
template-arb-file: app_pt.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n/generated
nullable-getter: false
preferred-supported-locales:
  - pt
=======
template-arb-file: app_pt_BR.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: true
nullable-getter: false
preferred-supported-locales:
>>>>>>> origin/codex/add-localization-configuration-and-files
  - pt_BR
  - en
  - es
untranslated-messages-file: build/l10n_untranslated.txt
